name: Build and Publish Worker Docker Image

# refer to https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml 

on:
  workflow_dispatch:
  push:
    tags:
      - worker@*

env:
  TAG_VERSION:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ vars.DOCKER_HUB_USER }}/${{ env.IMAGE_NAME }}
        
      # - name: Get Time
      #   id: time
      #   uses: nanzm/get-time-action@v1.1
      #   with:
      #     timeZone: 8
      #     format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Get version
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/worker@}" >> $GITHUB_ENV

      - name: Cache Rust dependecies
        uses: actions/cache@v4
        with:
          path: /cache
          key: ${{ runner.os }}-rust-${{ hashFiles('**/packages/worker/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-rust-
        
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: sepveneto/br-worker:latest,sepveneto/br-worker:${{ env.TAG_VERSION }}
          target: worker-deploy
        
      # sync image to aliyun
      - name: Login to aliyun
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ vars.ALIYUN_REGISTRY }}
          username: ${{ vars.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PWD }}
          logout: false

      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          skopeo copy docker://docker.io/sepveneto/br-worker:latest docker://registry.cn-hangzhou.aliyuncs.com/sepveneto/br-worker:latest
          skopeo copy docker://docker.io/sepveneto/br-worker:${{ env.TAG_VERSION }} docker://registry.cn-hangzhou.aliyuncs.com/sepveneto/br-worker:${{ env.TAG_VERSION }}
