name: Publish core to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - core@*

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # - name: Setup pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0 
          registry-url: https://registry.npmjs.org

      # - name: Get pnpm store directory
      #   id: pnpm-cache
      #   run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      # - name: Setup pnpm cache
      #   uses: actions/cache@v3
      #   with:
      #     path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
      #     key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-store-
      
      - name: Check OIDC token
        run: |
          curl -v -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" https://registry.npmjs.org/-/whoami
      
      - name: Force clean npm auth (required for OIDC)
        run: |
          rm -f ~/.npmrc
          rm -f ~/.pnpmrc

      - name: Build and Publish
        # run: sh ./scripts/publish-core.sh
        run: |
          npm i -g pnpm@9
          pnpm i --frozen-lockfile

          cd packages/core

          pnpm build

          npm publish --no-git-checks --access public

          echo "âœ… Publish completed"